on:
  workflow_dispatch:
    inputs:
      hax:
        description: "Hax"
        type: "string"
        default: "main"
      charon:
        description: "Charon"
        type: "string"
        default: "main"
      eurydice:
        description: "Eurydice"
        type: "string"
        default: "main"
      libcrux:
        description: "Libcrux"
        type: "string"
        default: "dev"
      bertie:
        description: "Bertie"
        type: "string"
        default: "main"

jobs:
  test:
    runs-on: [self-hosted, linux, nix]
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: update
        run: ./update.sh
        env:
          HAX_BRANCH: ${{ inputs.hax }}
          CHARON_BRANCH: ${{ inputs.charon }}
          EURYDICE_BRANCH: ${{ inputs.eurydice }}
          LIBCRUX_BRANCH: ${{ inputs.libcrux }}
          BERTIE_BRANCH: ${{ inputs.bertie }}

      - name: generate zulip message
        run: |
          {
            echo 'MSG<<EOF'
            echo "*Manual run*"
            nix shell nixpkgs#jq --command ./message.sh
            echo EOF
          } >> "$GITHUB_ENV"
        env:
          RUN: ${{ github.run_id }}

      - name: zulip info message
        uses: slackapi/slack-github-action@v1.25.0
        with:
          payload: |
            { "text": ${{ toJSON(env.MSG) }} }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.ZULIP_WEBHOOK_URL }}

      - name: zulip error message
        if: ${{ failure() }}
        uses: slackapi/slack-github-action@v1.25.0
        with:
          payload: |
            { "text": "Unexpected Error: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}" }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.ZULIP_WEBHOOK_URL }}
