on:
  workflow_dispatch:
    inputs:
      hax:
        description: "Hax"
        type: "string"
        default: "main"
      charon:
        description: "Charon"
        type: "string"
        default: "main"
      aeneas:
        description: "Aeneas"
        type: "string"
        default: "main"
      eurydice:
        description: "Eurydice"
        type: "string"
        default: "main"

jobs:
  test:
    runs-on: [self-hosted, linux, nix]
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: update
        run: ./update.sh
        env:
          HAX_BRANCH: ${{ inputs.hax }}
          CHARON_BRANCH: ${{ inputs.charon }}
          AENEAS_BRANCH: ${{ inputs.aeneas }}
          EURYDICE_BRANCH: ${{ inputs.eurydice }}
